### ISSUE TITLE
Missing recent iOS user agent regexes

### ISSUE THREAD

**Issue by mrfelton** [totpero/DeviceDetector.NET#25]
Current device detection is lacking lots of newer user agents and browser version (eg, latest iOS).

Considering leveraging https://github.com/ua-parser/uap-core for up to date data without needing to maintain that data yourself.

**Comment by Findus23** [comment]
Hi @mrfelton,

Just FYI, the parent project https://github.com/matomo-org/device-detector should be up-to-date with newer user agents. So it should be possible to update the rules here.

You can test the rules from the PHP project here and report missing user agents as github issues:
https://devicedetector.lw1.at/

**Comment by totpero** [comment]
Hi @mrfelton,
What @Findus23 is true, the original project with all yaml file up-to-date is the matomo-org project, this is only the .net port of php version.
The yaml file can be update in [this project folder](https://github.com/totpero/DeviceDetector.NET/tree/master/DeviceDetector.NET/regexes)
Anyone can create PR with the up-to-date file from the original [repo ](https://github.com/matomo-org/device-detector).
When I created this library was because in .NET i can't find advance user agents parser for free.
For example: https://51degrees.com/device-detection

Fell free to contribute, I will appreciate.
Thanks.

**Comment by mrfelton** [comment]
Here is a PR that updates the regexes:

https://github.com/totpero/DeviceDetector.NET/pull/26

**Comment by totpero** [comment]
I have update all regexes to last version from original php repo. 👍
