### ISSUE TITLE
Plan for Google's deprecation of UserAgent and introduction of new User-Agent Client Hints

### ISSUE THREAD

**Issue by steelsteed** [totpero/DeviceDetector.NET#53]
https://blog.chromium.org/2021/05/update-on-user-agent-string-reduction.html

and

https://wicg.github.io/ua-client-hints/

So like everything, its out with the old, and in with the new.
The snag is that Client Hints appears to be a very complicated solution to the problem.
Will a library like this support his in future ? Because without said support, the accuracy and usefulness of this Nuget would die over time.

Am interested in your feedback/thoughts on this matter

Thanks,

Steed.

**Comment by totpero** [comment]
Hi @steelsteed 

Yes this library will support [ClientHints ](https://github.com/matomo-org/device-detector/blob/master/ClientHints.php)because the original php library already implement this feature .
I plan to upgrade this library to last php version with all the features and changes but I'm busy now but I will try to do this upgrade.

Thank for the suggestion 👍

**Comment by totpero** [comment]
Hi @valgen ,
Now I try to do this implementation on v6 branch.

**Comment by totpero** [comment]
Hi @steelsteed , @valgen ,

I just release new version [v6.1.0](https://github.com/totpero/DeviceDetector.NET/releases/tag/v6.1.0), this version include Client Hints feature.

Test if is ok,
Thanks 👍
