### ISSUE TITLE
iPhone IOS version not detected

### ISSUE THREAD

**Issue by rogerfar** [totpero/DeviceDetector.NET#70]
I am trying to parse this user agent:
`Mozilla/5.0+(iPhone;+CPU+iPhone+OS+13_4+like+Mac+OS+X)+AppleWebKit/605.1.15+(KHTML,+like+Gecko)+CriOS/77.0.3865.103+Mobile/15E148+Safari/605.1`

When I use the PHP version:
![image](https://github.com/totpero/DeviceDetector.NET/assets/1142915/56bccb2c-eab8-4d3b-be09-88d8ebcb1402)
https://devicedetector.lw1.at/Mozilla%2F5.0+(iPhone;+CPU+iPhone+OS+13_4+like+Mac+OS+X)+AppleWebKit%2F605.1.15+(KHTML,+like+Gecko)+CriOS%2F77.0.3865.103+Mobile%2F15E148+Safari%2F605.1

But when using C# latest version:
![image](https://github.com/totpero/DeviceDetector.NET/assets/1142915/a0dd2996-d1d8-4747-b2cd-490ee229e6ac)
https://dotnetfiddle.net/LIV2yB

**Comment by totpero** [comment]
Hi @rogerfar,

Your problem is because your User Agent string contains `+` instead of  space character.
If you replace the + with space like this:
`Mozilla/5.0 (iPhone; CPU iPhone OS 13_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/77.0.3865.103 Mobile/15E148 Safari/605.1` 
the result will be the same:
![image](https://github.com/totpero/DeviceDetector.NET/assets/1710257/eb826767-f197-43eb-8356-b6bbd4d1a6e5)
The `+` character is user to encode space from URL on https://devicedetector.lw1.at

👍
